name: Generator

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: Install dependencies
        run : |
          yarn install
          pip3 install edge-tts --break-system-packages

      - name: Generate voice
        run: |
          yarn gen

      - name: "Jekyll theme"
        run: mv ./_config.temp.yml ./dist/_config.yml

      - name: Deploy github pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          enable_jekyll: true

